import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>YelpCamp | Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>YelpCamp</h1>
    </>
  )
}

// TODO: CRUD

// C -> POST  /campgrounds       ✅
// R -> GET   /campgrounds       ✅
// U -> PATCH /campgrounds/[id]  ❌
// D -> DELETE /campgrounds/[id] ❌
