import Head from 'next/head'
import Image from 'next/image'
import ButtonOutline from '../components/ButtonOutline'
import ladingIllustrastion from '/public/illustrations/landing.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>YelpCamp | Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='flex flex-col gap-10 py-10 md:flex-row lg:gap-16 lg:py-20'>
        <div className='flex-1'>
          <h3 className='mb-5 font-volkhov text-4xl font-bold leading-tight lg:text-5xl lg:leading-snug xl:mb-10 xl:text-6xl'>
            Get started your exciting{' '}
            <span className='text-brand '>journey</span> with us.
          </h3>
          <p className='mb-10 text-paragraph lg:text-lg lg:leading-loose xl:mb-16 xl:text-xl xl:leading-loose'>
            A Team of experienced tourism professionals will provide you with
            the best advice and tips for your desire place.
          </p>
          <ButtonOutline text='Discover Now' />
        </div>
        <div className='flex-1'>
          <Image
            className='w-sm md:w-full'
            src={ladingIllustrastion}
            alt='df'
          />
        </div>
      </section>
    </>
  )
}

// TODO: CRUD

// C -> POST  /campgrounds       ✅
// R -> GET   /campgrounds       ✅
// U -> PATCH /campgrounds/[id]  ✅
// D -> DELETE /campgrounds/[id] ✅
