import Head from 'next/head'
import Image from 'next/image'
import ButtonOutline from '../components/ButtonOutline'
import Button from '../components/Button'
import ladingIllustrastion from '/public/illustrations/landing.svg'
import { FaChevronDown } from 'react-icons/fa'
import signupicon from '/public/icons/things_to_do_signup.svg'
import moneyicon from '/public/icons/things_to_do_money.svg'
import travelicon from '/public/icons/things_to_do_travel.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>YelpCamp | Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='grid gap-10 py-10 lg:gap-16 lg:py-16'>
        <div className='flex flex-col gap-10 md:flex-row'>
          <div className='flex-1'>
            <h3 className='mb-5 font-volkhov text-4xl font-bold leading-tight lg:text-5xl lg:leading-snug xl:mb-10 xl:text-6xl'>
              Get started your exciting{' '}
              <span className='text-brand '>journey</span> with us.
            </h3>
            <p className='mb-10 text-paragraph lg:text-lg lg:leading-loose xl:mb-16 xl:text-xl xl:leading-loose'>
              A Team of experienced tourism professionals will provide you with
              the best advice and tips for your desire place.
            </p>
            <ButtonOutline text='Discover Now' />
          </div>
          <div className='flex-1'>
            <Image
              className='w-sm md:w-full'
              src={ladingIllustrastion}
              alt='df'
            />
          </div>
        </div>
        <form className='mx-auto flex max-w-screen-md flex-wrap items-center gap-8 rounded-lg bg-[#fff] p-6 drop-shadow-xl md:flex-row md:justify-around md:py-8'>
          <div className='flex flex-col items-start'>
            <div className='flex items-center gap-1'>
              <select
                defaultValue={'null'}
                name='location'
                id='location'
                className='cursor-pointer appearance-none bg-transparent'
              >
                <option value='null' disabled>
                  Location
                </option>
                <option value='Hello'>Hello</option>
              </select>
              <label htmlFor='location'>
                <FaChevronDown className='text-xs text-brand' />
              </label>
            </div>
            <p className='text-sm text-paragraph'>Where are you going</p>
          </div>
          <div className='flex flex-col items-start'>
            <div className='flex items-center gap-1'>
              <input
                type={'date'}
                name='date'
                id='date'
                className='cursor-pointer appearance-none bg-transparent'
              />
              <label htmlFor='date'>
                <FaChevronDown className='text-xs text-brand' />
              </label>
            </div>
            <p className='text-sm text-paragraph'>When will you go</p>
          </div>
          <div className='flex flex-col items-start'>
            <div className='flex items-center gap-1'>
              <select
                defaultValue={'null'}
                name='guests'
                id='guests'
                className='cursor-pointer appearance-none bg-transparent'
              >
                <option value='null' disabled>
                  Guest
                </option>
                <option value='Hello'>Hello</option>
              </select>
              <label htmlFor='guests'>
                <FaChevronDown className='text-xs text-brand' />
              </label>
            </div>
            <p className='text-sm text-paragraph'>Number of guests</p>
          </div>
          <Button text='Explore Now' />
        </form>
      </section>
      <section className='bg-secondaryBg p-7'>
        <h3 className='mb-2 text-center font-volkhov text-2xl font-extrabold'>
          Things you need <span className='text-brand'>to do</span>
        </h3>
        <p className='mb-5 text-center text-base text-paragraph'>
          We ensure that you&apos;ll embark on a perfectly planned, safe
          vacation at a price you can afford.
        </p>
        <div className='flex flex-wrap gap-5'>
          <div className='max-w-xs rounded-lg bg-white p-6 shadow-lg'>
            <Image src={signupicon} alt='sign up icon' className='mb-4' />
            <h5 className='mb-2 text-lg font-bold'>Sign Up</h5>
            <p className='text-sm text-paragraph'>
              Completes all the work associated with planning and processing
            </p>
          </div>
          <div className='max-w-xs rounded-lg bg-white p-6 shadow-lg '>
            <Image src={moneyicon} alt='sign up icon' className='mb-4' />
            <h5 className='mb-2 text-lg font-bold'>Worth of Money</h5>
            <p className='text-sm text-paragraph'>
              After successful access then book from exclusive deals & pricing
            </p>
          </div>
          <div className='max-w-xs rounded-lg bg-white p-6 shadow-lg '>
            <Image src={travelicon} alt='sign up icon' className='mb-4' />
            <h5 className='mb-2 text-lg font-bold'>Exciting Travel</h5>
            <p className='text-sm text-paragraph'>
              Start and explore a wide range of exciting travel experience.
            </p>
          </div>
        </div>
      </section>
    </>
  )
}

// TODO: CRUD

// C -> POST  /campgrounds       ✅
// R -> GET   /campgrounds       ✅
// U -> PATCH /campgrounds/[id]  ✅
// D -> DELETE /campgrounds/[id] ✅
